apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.microservice.postgres.pv.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  capacity:
    storage: {{ .Values.microservice.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.microservice.postgres.pv.path }}
