apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.microservice.postgres.pvc.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.microservice.postgres.storage }}
