apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
stringData:
  username: {{ .Values.microservice.postgres.username }}
  password: {{ .Values.microservice.postgres.password }}
