apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-postgres-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data:
  username: {{ .Values.microservice.postgres.user | b64enc }}
  password: {{ .Values.microservice.postgres.password | b64enc }}
