apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: name-store-fb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: masum012924/name-store-backend:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_HOST
              value: mongodb-service  # MongoDB service name in Kubernetes
            - name: MONGO_DATABASE
              value: mydatabase  # Database name in MongoDB
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: name-store-fb
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Backend should be accessible only within the cluster

