apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: registration-fb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: masum012924/registration-backend:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_HOST
              value: postgres-service   # PostgreSQL service name in Kubernetes
            - name: POSTGRES_DATABASE
              value: mydatabase  # Database name in PostgreSQL
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: registration-fb
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Backend should be accessible only within the cluster

