apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: name-store-fb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: masum012924/name-store-frontend:latest
          ports:
            - containerPort: 5000  # Ensure your frontend actually runs on this port
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: name-store-fb
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Exposes service inside cluster on port 80
      targetPort: 5000  # Maps to frontend container port
      nodePort: 30050  # Exposed externally on all nodes
  type: NodePort  # Exposes service on a fixed port (30050)
