apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registration-py
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/masumshamsur/registration-py_PostgreSQL-Docker-K8S-Helm-GitHubAction-ArgoCD.git
    targetRevision: develop
    path: registration-py-chart-all-togather
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: registration-py-postgres

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
