name: CI/CD Pipeline
on:
    workflow_dispatch:
    push:
        branches:
            - develop

jobs:            
   build-and-push:
    name: Build and Push Docker Images
    runs-on : ubuntu-latest

    steps:
        # Checkout the repository
        - name: Checkout Code
          uses: actions/checkout@v4