apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: {{ .Values.microservice.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: {{ .Values.microservice.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: {{ .Values.microservice.namespace }}
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: {{ .Values.microservice.namespace }}
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.microservice.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: "{{ .Values.microservice.backend.image.repository }}:{{ .Values.microservice.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.microservice.backend.service.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_HOST
              value: {{ .Values.microservice.postgres.service.name }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.microservice.postgres.env.database }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.microservice.backend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.microservice.namespace }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.microservice.backend.service.port }}
      targetPort: {{ .Values.microservice.backend.service.port }}
  type: {{ .Values.microservice.backend.service.type }}
