name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  FRONTEND_IMAGE_NAME: user-registration-frontend
  BACKEND_IMAGE_NAME: user-registration-backend

jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Frontend - Build and Test

    steps:
        # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4
      
        # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

        #install dependencies
      - name: Install dependencies
        run: pip install -r frontend/requirements.txt

        #run frontend tests
      - name: Run frontend tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest frontend/tests/

  backend:
    runs-on: ubuntu-latest
    name: Backend - Build and Test

    # Define services
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: myUser
          POSTGRES_PASSWORD: myPass
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
        # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

        # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

        #install dependencies
      - name: Install dependencies
        run: pip install -r backend/requirements.txt

        #run backend tests
      - name: Run backend tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest backend/tests/
